var cordova_plugins = {
		'com.google.cordova.admob' : {
		onsale : true,
		cat : 'ad',
		name : 'AdMobPluginPro',
		intro : 'The best Plugin for Google AdMob, single line javascript code to display Banner and Interstitial. Any size, any position! Latest SDK for iOS and Android with Google Play Services. Compatible with Intel XDK and IBM worklight.',
		ios : true,
		android : true,
		win : false,
		price : 14.99,
		github_url : 'https://github.com/floatinghotpot/cordova-admob-pro',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.admob' : {
		onsale : true,
		cat : 'ad',
		name : 'AdMob Plugin',
		intro : 'The most popular AdMob Plugin, Banner and Interstitial.',
		ios : true,
		android : true,
		win : true,
		price : 0,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-admob',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.flurry' : {
		onsale : true,
		cat : 'ad',
		name : 'FlurryAds Plugin',
		intro : 'Plugin for Yahoo Flurry Ads, Banner, Interstitial and Video.',
		ios : true,
		android : true,
		win : false,
		price : 14.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-flurry',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.iad' : {
		onsale : true,
		cat : 'ad',
		name : 'iAd Plugin',
		intro : 'The No. 1 Plugin for Apple iAd in PhoneGap Build (iOS only)',
		ios : true,
		android : false,
		win : false,
		price : 0,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-iad',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.appleiap' : {
		onsale : true,
		cat : 'iap',
		name : 'Apple IAP Plugin',
		intro : 'Plugin for Apple In-App Purchase support (iOS only)',
		ios : true,
		android : false,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-appleiap',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.paypalmpl' : {
		onsale : true,
		cat : 'iap',
		name : 'PayPal MPL Plugin',
		intro : 'Add PayPal support with MPL SDK (Mobile Payment Library, not new SDK) to your cordova apps or games',
		ios : true,
		android : true,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-paypalmpl',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.lowlatencyaudio' : {
		onsale : true,
		cat : 'media',
		name : 'LowLatencyAudio Plugin',
		intro : 'Plugin to support Low Latency and Polyphonic Audio Playback on Android and iOS, must have for mobile apps/games, as HTML5 audio in mobile browsers is really poor. Also implemented same interface for HTML5 audio, useful when test in PC browser.',
		ios : true,
		android : true,
		win : false,
		price : 19.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-lowlatencyaudio',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.sms' : {
		onsale : true,
		cat : 'system',
		name : 'SMS Plugin',
		intro : 'Cordova plugin to send and manage SMS messages.',
		ios : false,
		android : true,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-sms',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.bluetooth' : {
		onsale : false,
		cat : 'system',
		name : 'Bluetooth Plugin',
		intro : 'Cordova plugin to manage bluetooth devices and connections.',
		ios : false,
		android : true,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-bluetooth',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.toast' : {
		onsale : false,
		cat : 'system',
		name : 'Toast Plugin',
		intro : 'Cordova plugin to show popup message with toast.',
		ios : false,
		android : true,
		win : false,
		price : 9.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-toast',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.facebook' : {
		onsale : false,
		cat : 'social',
		name : 'Facebook Plugin',
		intro : 'Cordova plugin to login and post to facebook.',
		ios : false,
		android : true,
		win : false,
		price : 19.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-facebook',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.twitter' : {
		onsale : false,
		cat : 'social',
		name : 'Twitter Plugin',
		intro : 'Cordova plugin to login and post to twitter.',
		ios : false,
		android : true,
		win : false,
		price : 19.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-facebook',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.socialsharing' : {
		onsale : false,
		cat : 'social',
		name : 'SocialSharing Plugin',
		intro : 'Cordova plugin to sharing picture, text and link to social media.',
		ios : true,
		android : true,
		win : true,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-socialsharing',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.wifiadmin' : {
		onsale : true,
		cat : 'network',
		name : 'Wifi Admin Plugin',
		intro : 'Cordova plugin to search and manage WiFi connections.',
		ios : false,
		android : true,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-wifi',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.httpd' : {
		onsale : true,
		cat : 'network',
		name : 'CorHttpd Plugin',
		intro : 'CorHttpd is an plugin to embed a web server into Cordova, to access local file or web content with HTTP protocol. It is used by the famous Meteor project.',
		ios : true,
		android : true,
		win : false,
		price : 29.99,
		github_url : 'https://github.com/floatinghotpot/cordova-httpd',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	},
	'com.rjfun.cordova.plugin.iflyspeech' : {
		onsale : true,
		cat : 'media',
		name : 'iFlySpeech Plugin',
		intro : 'Cordova plugin to support mobile speech recognizer and synthesizer with iFlyTek voice cloud service.',
		ios : true,
		android : true,
		win : false,
		price : 49.99,
		github_url : 'https://github.com/floatinghotpot/cordova-plugin-iflyspeech',
		paypal_url : 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW'
	}
};

