var cordova_plugins = {
	"com.google.cordova.admob" : {
		intro : "One of the most impressive advertising platforms currently available, AdMob's major claim to fame is its massive base of advertisers. It is owned by Google and provides an integrated software development kit to connect over popular mobile platforms including Android, iOS and Windows Phone. AdMob has a high CPC to help you get the best ROI.",
		signup_url : "http://www.admob.com/",
		logo : "img/logo_admob.jpg",
		onsale : true,
		cat : "ad",
		name : "AdMob PluginPro",
		desc : "The best plugin for Google AdMob, single line javascript code to display Banner and Interstitial. Any size, any position! Latest SDK for iOS and Android with Google Play Services. Compatible with Intel XDK and IBM worklight.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-admob-pro",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NRKTFZ88Q9KTW"
	},
	"com.rjfun.cordova.iad" : {
		intro : "Apple's iAd service. With iAd, you can get your message out to the millions of people using iPhone and iPad.",
		logo : "img/logo_iad.jpg",
		onsale : true,
		cat : "ad",
		name : "iAd PluginPro",
		desc : "The No.1 Plugin for Apple iAd in PhoneGap Build.",
		ios : true,
		android : false,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-iad-pro",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QHW9HFB2L8GUE"
	},
	"com.rjfun.cordova.flurryads" : {
		intro : "The team at Flurry has amassed a treasure trove of user data from more than 700 million smartphones and other mobile devices. Use it for interstitial, takeover and video ads on iOS and Android.",
		signup_url : "http://www.flurry.com/",
		logo : "img/logo_flurry.jpg",
		onsale : true,
		cat : "ad",
		name : "FlurryAds PluginPro",
		desc : "Plugin for Yahoo Flurry Ads, Banner, Interstitial and Video.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-flurry",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=C654HGZVC43T4"
	},
	"com.rjfun.cordova.facebookads" : {
		intro : "Extend the same rich targeting that exists on Facebook to your app. Over 1.5 million advertisers, Get access to Facebook advertisers looking to find their audience in your app. Choose from banner, interstitial and customizable native units.",
		signup_url : "https://developers.facebook.com/",
		logo : "img/logo_facebookads.jpg",
		onsale : true,
		cat : "ad",
		name : "FacebookAds PluginPro",
		desc : "Plugin for Facebook Audience Network Ads, Banner, Interstitial and Native Ad.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-facebookads",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H3EYC4JZNSRRS"
	},
	"com.rjfun.cordova.mmedia" : {
		intro : "Millennial Media is known for being the first mobile ad network that went to the next level through an initial public offering. This platform provides a wealth of research and intelligence, and you can use it to quickly set up a campaign for advertisers to compete for your business.",
		signup_url : "http://www.mmedia.com/",
		logo : "img/logo_mmedia.jpg",
		onsale : true,
		cat : "ad",
		name : "mMedia (Millennial Media) PluginPro",
		desc : "Using this cordova plugin for mMedia (Millennial Media), you can easily display Banner and full screen Video Ad with single line of javascript code.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-mmedia",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XJYYFV9XFF9U4"
	},
	"com.rjfun.cordova.mobfox" : {
		intro : "Looking to gain absolute control over the ads shown in your mobile app? MobFox supports more than 10,000 publishers. It features an open-source software development kit, dynamic floor pricing and real time bidding through more than 30 integrated ad networks.",
		signup_url : "http://www.mobfox.com/",
		logo : "img/logo_mobfox.jpg",
		onsale : true,
		cat : "ad",
		name : "MobFox PluginPro",
		desc : "Using this cordova plugin for MobFox, you can easily display Banner, Interstitial and Video Ad with single line of javascript code.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-mobfox-pro",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HJCR6JFWTNNFW"
	},
	"com.rjfun.cordova.mopub" : {
		intro : "This mobile ad exchange company has momentum: Within 18 months, and with just 65 employees, it has hit a $100 million revenue run rate. It capitalized on the rise of real-time bidding, offering a transparent exchange.",
		signup_url : "http://www.mopub.com/",
		logo : "img/logo_mopub.jpg",
		onsale : true,
		cat : "ad",
		name : "MoPub PluginPro",
		desc : "Using this cordova plugin for MoPub, you can easily display Banner, Interstitial and Video Ad with single line of javascript code.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-mopub",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UQE6P4NG6NKYS"
	},
	"com.rjfun.cordova.vungle" : {
		intro : "Not all ads are boring to users. Think of all the people who pay attention to the amazing ads that air during the Super Bowl, for example. Vungle is devoted to helping you monetize your app with interesting and engaging video ads that your end users will enjoy viewing.",
		signup_url : "http://www.vungle.com/",
		onsale : false,
		cat : "ad",
		name : "Vungle Plugin",
		desc : "Using this cordova plugin for Vungle, you can easily display Video Ad with single line of javascript code.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-vungle",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HDGF755KQQWRY"
	},
	"com.rjfun.cordova.tapjoy" : {
		intro : "If you have developed a mobile game, you'll want to consider Tapjoy because of its expertise with in-app purchases. It enables your users to earn virtual currency that they can cash in for content in more than 20,000 games to date.",
		signup_url : "http://www.tapjoy.com/",
		onsale : false,
		cat : "ad",
		name : "TapJoy Plugin",
		desc : "Using this cordova plugin for TapJoy, you can easily display Banner, Interstitial and Video Ad with single line of javascript code.",
		ios : true,
		android : true,
		win : false,
		price : 20.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-tapjoy",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WRT588EJ4BHJE"
	},
	"com.rjfun.cordova.plugin.appleiap" : {
		logo : "img/logo_apple_iap.jpg",
		onsale : true,
		cat : "iap",
		name : "Apple IAP Plugin",
		desc : "In-App Purchase with Apple IAP (iOS only)",
		ios : true,
		android : false,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-appleiap",
		paypal_url : ""
	},
	"com.rjfun.cordova.plugin.paypalmpl" : {
		logo : "img/logo_paypal.jpg",
		onsale : true,
		cat : "iap",
		name : "PayPal MPL Plugin",
		desc : "In-app Purchase with PayPal. Add PayPal support with MPL (Mobile Payment Library) SDK.",
		ios : true,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-paypalmpl",
		paypal_url : ""
	},
	"com.rjfun.cordova.plugin.lowlatencyaudio" : {
		logo : "img/logo_audio.jpg",
		onsale : true,
		cat : "media",
		name : "LowLatencyAudio Plugin",
		desc : "Must have for mobile games. Plugin to support Low Latency and Polyphonic Audio Playback on Android and iOS, as HTML5 audio in mobile browsers is really poor. Also implemented same interface for HTML5 audio, useful when test in PC browser.",
		ios : true,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-lowlatencyaudio",
		paypal_url : ""
	},
	"com.rjfun.cordova.sms" : {
		logo : "img/logo_sms.jpg",
		onsale : true,
		cat : "system",
		name : "SMS Plugin",
		desc : "Cordova plugin to send and manage SMS messages.",
		ios : false,
		android : true,
		win : false,
		price : 30.00,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-sms",
		paypal_url : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=86JSRPJDQUMRU"
	},
	"com.rjfun.cordova.plugin.bluetooth" : {
		onsale : false,
		cat : "system",
		name : "Bluetooth Plugin",
		desc : "Cordova plugin to manage bluetooth devices and connections.",
		ios : false,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-bluetooth",
		paypal_url : ""
	},
	"com.rjfun.cordova.plugin.toast" : {
		onsale : false,
		cat : "system",
		name : "Toast Plugin",
		desc : "Cordova plugin to show popup message with toast.",
		ios : false,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-toast",
		paypal_url : ""
	},
	"com.rjfun.cordova.plugin.facebook" : {
		onsale : false,
		cat : "social",
		name : "Facebook Plugin",
		desc : "Cordova plugin to login and post to facebook.",
		ios : false,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-facebook",
		paypal_url : ""
	},
	"com.rjfun.cordova.twitter" : {
		onsale : false,
		cat : "social",
		name : "Twitter Plugin",
		desc : "Cordova plugin to login and post to twitter.",
		ios : false,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-facebook",
		paypal_url : ""
	},
	"com.rjfun.cordova.socialsharing" : {
		onsale : false,
		cat : "social",
		name : "SocialSharing Plugin",
		desc : "Cordova plugin to sharing picture, text and link to social media.",
		ios : true,
		android : true,
		win : true,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-socialsharing",
		paypal_url : "0"
	},
	"com.rjfun.cordova.plugin.wifiadmin" : {
		logo : "img/logo_wifi.jpg",
		onsale : true,
		cat : "system",
		name : "Wifi Admin Plugin",
		desc : "Search and manage WiFi connections.",
		ios : false,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-wifi",
		paypal_url : ""
	},
	"com.rjfun.cordova.httpd" : {
		intro : "Wanna develop app to enable accessing files in smartphone from remote browser? Try CorHttpd.",
		logo : "img/logo_corhttpd.jpg",
		onsale : true,
		cat : "system",
		name : "CorHttpd Plugin",
		desc : "CorHttpd is an plugin to embed a web server into Cordova, to access local file or web content with HTTP protocol. It is used by the famous Meteor project.",
		ios : true,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-httpd",
		paypal_url : ""
	},
	"com.rjfun.cordova.plugin.iflyspeech" : {
		logo : "img/logo_speech.jpg",
		onsale : true,
		cat : "media",
		name : "iFlySpeech Plugin",
		desc : "Wanna talk to your phone? Cordova plugin to support mobile speech recognizer and synthesizer with iFlyTek voice cloud service.",
		ios : true,
		android : true,
		win : false,
		price : 0,
		github_url : "https://github.com/floatinghotpot/cordova-plugin-iflyspeech",
		paypal_url : ""
	}
};

